EXPERIMENT 1

Aim:
To understand and apply basic array and matrix operations in Python, focusing on foundational functions for manipulating numerical data.

Objectives:

1. Familiarize with core array and matrix functions in Python using NumPy, such as add, dot, cross, and others.
2. Perform element-wise operations, matrix transformations, and vector manipulations to understand data structure handling.
3. Explore functions that enable reshaping, transposing, and combining arrays and matrices.
4. Build proficiency in foundational operations as a basis for further applications in data processing and analysis.

In [1]:
import numpy as np
from math import *

In [2]:
arr_id=np.array([2,4,6,8])
arr_id

array([2, 4, 6, 8])

In [3]:
sum= np.sum(arr_id)
sum

20

In [4]:
mean=np.mean(arr_id)
mean

5.0

In [5]:
EWA=np.add(arr_id,10)
EWA

array([12, 14, 16, 18])

In [6]:
arr_2d = np.array([[1,2,3,4],[5,6,7,8]])
arr_2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
A= arr_2d
A

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
AT= np.transpose(A)
AT

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [9]:
ADD= np.add(A,A)
ADD

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [10]:
ADDT=np.add(A,AT)
ADDT

ValueError: operands could not be broadcast together with shapes (2,4) (4,2) 

In [11]:
mul=np.dot(A,AT)
mul

array([[ 30,  70],
       [ 70, 174]])

In [12]:
mul2=np.dot(A,A)
mul2

ValueError: shapes (2,4) and (2,4) not aligned: 4 (dim 1) != 2 (dim 0)